sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version

  - docker build -t ansible_alpine3 .

script:
  - docker run -i ansible_alpine3 > result-alpine3

  - echo "==> Validating the test results..."
  - sh -c "[ -s result-alpine3             ]"
